-- ===================================================================
-- OptiTeach: PostgreSQL relational schema (reference DDL)
--
-- GENERATED by database/scripts/export_sql_reference.py from a database
-- migrated with `alembic upgrade head`. Includes tables, constraints,
-- indexes, views, the materialized view, functions, the procedure,
-- triggers, row-level security policies and GRANTs to the optiteach_app /
-- optiteach_readonly roles. Source of truth is database/migrations/ -
-- regenerate, don't edit.
-- ===================================================================

--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: fn_audit_row_change(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_audit_row_change() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
    v_old jsonb;
    v_new jsonb;
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN v_old := to_jsonb(OLD); END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') THEN v_new := to_jsonb(NEW); END IF;
    IF TG_OP = 'UPDATE' AND v_old = v_new THEN
        RETURN NULL;  -- ignore no-op updates
    END IF;

    INSERT INTO audit_log (table_name, operation, row_id, old_data, new_data, changed_by, changed_at)
    VALUES (TG_TABLE_NAME, TG_OP, COALESCE(v_new ->> 'id', v_old ->> 'id'), v_old, v_new,
            NULLIF(current_setting('app.user_id', true), ''), timezone('utc', now()));
    RETURN NULL;
END $$;

--
-- Name: fn_performance_weakness(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_performance_weakness() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
    v_threshold double precision;
BEGIN
    SELECT tc.revision_threshold_score INTO v_threshold
    FROM assessments a
    JOIN teacher_constraints tc ON tc.course_id = a.course_id
    WHERE a.id = NEW.assessment_id;

    NEW.weakness_flag := NEW.average_score < COALESCE(v_threshold, 60.0);
    RETURN NEW;
END $$;

--
-- Name: fn_prerequisite_chain(character varying); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_prerequisite_chain(p_concept_id character varying) RETURNS TABLE(prerequisite_id character varying, prerequisite_name character varying, depth integer, path text)
    LANGUAGE sql STABLE
    SET search_path TO 'public', 'pg_temp'
    AS $$
    WITH RECURSIVE chain(cid, lvl, trail, names) AS (
        SELECT p.prerequisite_id, 1,
               ARRAY[p.concept_id::text, p.prerequisite_id::text],
               ARRAY[t.name::text, pc.name::text]
        FROM prerequisites p
        JOIN concepts t  ON t.id = p.concept_id
        JOIN concepts pc ON pc.id = p.prerequisite_id
        WHERE p.concept_id = p_concept_id
        UNION ALL
        SELECT p.prerequisite_id, ch.lvl + 1,
               ch.trail || p.prerequisite_id::text,
               ch.names || pc.name::text
        FROM chain ch
        JOIN prerequisites p ON p.concept_id = ch.cid
        JOIN concepts pc ON pc.id = p.prerequisite_id
        WHERE p.prerequisite_id::text <> ALL (ch.trail)
    )
    SELECT s.cid, s.cname, s.lvl, s.path
    FROM (
        SELECT DISTINCT ON (ch.cid)
               ch.cid::varchar AS cid, c.name::varchar AS cname, ch.lvl,
               array_to_string(ch.names, ' <- ') AS path
        FROM chain ch
        JOIN concepts c ON c.id = ch.cid
        ORDER BY ch.cid, ch.lvl
    ) s
    ORDER BY s.lvl, s.cname;
$$;

--
-- Name: fn_prerequisite_guard(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_prerequisite_guard() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
    v_course_concept varchar;
    v_course_prereq  varchar;
BEGIN
    SELECT u.course_id INTO v_course_concept
    FROM concepts c JOIN topics t ON t.id = c.topic_id JOIN units u ON u.id = t.unit_id
    WHERE c.id = NEW.concept_id;

    SELECT u.course_id INTO v_course_prereq
    FROM concepts c JOIN topics t ON t.id = c.topic_id JOIN units u ON u.id = t.unit_id
    WHERE c.id = NEW.prerequisite_id;

    IF v_course_concept IS DISTINCT FROM v_course_prereq THEN
        RAISE EXCEPTION 'Prerequisite % and concept % belong to different courses',
            NEW.prerequisite_id, NEW.concept_id
            USING ERRCODE = 'check_violation';
    END IF;

    PERFORM pg_advisory_xact_lock(hashtext('prerequisites:' || v_course_concept));

    -- Edge (concept_id, prerequisite_id) means prerequisite -> concept.
    -- It closes a cycle iff concept_id is already upstream of prerequisite_id.
    IF EXISTS (
        WITH RECURSIVE upstream(cid) AS (
            SELECT p.prerequisite_id FROM prerequisites p WHERE p.concept_id = NEW.prerequisite_id
            UNION
            SELECT p.prerequisite_id FROM prerequisites p JOIN upstream u ON p.concept_id = u.cid
        )
        SELECT 1 FROM upstream WHERE cid = NEW.concept_id
    ) THEN
        RAISE EXCEPTION 'Prerequisite edge % -> % would create a cycle',
            NEW.prerequisite_id, NEW.concept_id
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END $$;

--
-- Name: fn_refresh_course_dashboard(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_refresh_course_dashboard() RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
        BEGIN
            REFRESH MATERIALIZED VIEW CONCURRENTLY mv_course_dashboard;
        END $$;

--
-- Name: fn_set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public', 'pg_temp'
    AS $$
BEGIN
    NEW.updated_at := timezone('utc', now());
    RETURN NEW;
END $$;

--
-- Name: fn_threshold_recompute_weakness(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_threshold_recompute_weakness() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public', 'pg_temp'
    AS $$
BEGIN
    UPDATE performance p
    SET weakness_flag = p.average_score < NEW.revision_threshold_score
    FROM assessments a
    WHERE a.id = p.assessment_id
      AND a.course_id = NEW.course_id
      AND p.weakness_flag IS DISTINCT FROM (p.average_score < NEW.revision_threshold_score);
    RETURN NULL;
END $$;

--
-- Name: fn_time_pressure(character varying); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_time_pressure(p_course_id character varying) RETURNS TABLE(remaining_topics integer, remaining_periods integer, remaining_required_minutes integer, remaining_available_minutes integer, pressure_ratio numeric, pressure_status text)
    LANGUAGE sql STABLE
    SET search_path TO 'public', 'pg_temp'
    AS $$
    WITH demand AS (
        SELECT COUNT(*)::int AS n_topics,
               COALESCE(SUM(CASE WHEN t.allocated_minutes > 0 THEN t.allocated_minutes
                                 ELSE t.estimated_minutes END), 0)::int AS minutes
        FROM topics t JOIN units u ON u.id = t.unit_id
        WHERE u.course_id = p_course_id AND t.status <> 'completed'
    ), capacity AS (
        SELECT COUNT(*)::int AS n_periods, COALESCE(SUM(cs.duration_minutes), 0)::int AS minutes
        FROM class_sessions cs
        WHERE cs.course_id = p_course_id AND cs.status = 'scheduled'
    )
    SELECT d.n_topics, c.n_periods, d.minutes, c.minutes,
           ROUND(d.minutes::numeric / NULLIF(c.minutes, 0), 2),
           CASE
               WHEN c.minutes = 0 AND d.minutes > 0              THEN 'over_capacity'
               WHEN c.minutes = 0                               THEN 'complete'
               WHEN d.minutes::numeric / c.minutes > 1.0         THEN 'over_capacity'
               WHEN d.minutes::numeric / c.minutes > 0.9         THEN 'high_pressure'
               WHEN d.minutes::numeric / c.minutes > 0.7         THEN 'balanced'
               ELSE 'healthy'
           END
    FROM demand d CROSS JOIN capacity c;
$$;

--
-- Name: sp_record_concept_performance(character varying, character varying, double precision, integer, text); Type: PROCEDURE; Schema: public; Owner: -
--

CREATE PROCEDURE public.sp_record_concept_performance(IN p_assessment_id character varying, IN p_concept_id character varying, IN p_average_score double precision, IN p_sample_size integer, IN p_common_errors text)
    LANGUAGE plpgsql
    SET search_path TO 'public', 'pg_temp'
    AS $$
BEGIN
    PERFORM 1 FROM assessments WHERE id = p_assessment_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Assessment % not found', p_assessment_id USING ERRCODE = 'no_data_found';
    END IF;

    INSERT INTO performance (id, concept_id, assessment_id, average_score, sample_size, common_errors, recorded_at)
    VALUES (gen_random_uuid()::text, p_concept_id, p_assessment_id, p_average_score,
            p_sample_size, p_common_errors, timezone('utc', now()))
    ON CONFLICT ON CONSTRAINT uq_concept_assessment_performance DO UPDATE
        SET average_score = EXCLUDED.average_score,
            sample_size   = EXCLUDED.sample_size,
            common_errors = EXCLUDED.common_errors,
            recorded_at   = EXCLUDED.recorded_at;

    UPDATE assessments SET status = 'completed'
    WHERE id = p_assessment_id AND status <> 'completed';
END $$;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assessments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessments (
    id character varying(36) NOT NULL,
    course_id character varying(36) NOT NULL,
    title character varying(255) NOT NULL,
    assessment_type character varying(50) NOT NULL,
    max_marks double precision NOT NULL,
    scheduled_date timestamp without time zone,
    status character varying(50),
    created_at timestamp without time zone,
    CONSTRAINT check_assessment_status CHECK (((status)::text = ANY ((ARRAY['upcoming'::character varying, 'completed'::character varying])::text[]))),
    CONSTRAINT check_assessment_type CHECK (((assessment_type)::text = ANY ((ARRAY['quiz'::character varying, 'assignment'::character varying, 'midterm'::character varying, 'final'::character varying])::text[]))),
    CONSTRAINT check_positive_max_marks CHECK ((max_marks > (0)::double precision))
);

--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    table_name character varying(63) NOT NULL,
    operation character varying(6) NOT NULL,
    row_id character varying(36),
    old_data jsonb,
    new_data jsonb,
    changed_by character varying(36),
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT check_audit_operation CHECK (((operation)::text = ANY ((ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying])::text[])))
);

--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: audit_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_log_id_seq OWNED BY public.audit_log.id;

--
-- Name: class_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_sessions (
    id character varying(36) NOT NULL,
    course_id character varying(36) NOT NULL,
    session_number integer NOT NULL,
    scheduled_date timestamp without time zone,
    duration_minutes integer NOT NULL,
    current_topic_id character varying(36),
    status character varying(50),
    CONSTRAINT check_positive_session_duration CHECK ((duration_minutes > 0)),
    CONSTRAINT check_positive_session_number CHECK ((session_number >= 1)),
    CONSTRAINT check_session_status CHECK (((status)::text = ANY ((ARRAY['scheduled'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying])::text[])))
);

--
-- Name: concept_outcomes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.concept_outcomes (
    concept_id character varying(36) NOT NULL,
    outcome_id character varying(36) NOT NULL
);

--
-- Name: concepts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.concepts (
    id character varying(36) NOT NULL,
    topic_id character varying(36) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    difficulty integer,
    importance integer,
    concept_type character varying(50),
    order_index integer,
    CONSTRAINT check_concept_type CHECK (((concept_type)::text = ANY ((ARRAY['conceptual'::character varying, 'procedural'::character varying, 'problem_solving'::character varying, 'practical'::character varying, 'analytical'::character varying, 'revision'::character varying])::text[]))),
    CONSTRAINT check_difficulty_range CHECK (((difficulty >= 1) AND (difficulty <= 5))),
    CONSTRAINT check_importance_range CHECK (((importance >= 1) AND (importance <= 5)))
);

--
-- Name: course_outcomes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_outcomes (
    id character varying(36) NOT NULL,
    course_id character varying(36) NOT NULL,
    code character varying(20) NOT NULL,
    description text NOT NULL,
    bloom_level character varying(50),
    CONSTRAINT check_bloom_level CHECK (((bloom_level)::text = ANY ((ARRAY['Remember'::character varying, 'Understand'::character varying, 'Apply'::character varying, 'Analyze'::character varying, 'Evaluate'::character varying, 'Create'::character varying])::text[])))
);

--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id character varying(36) NOT NULL,
    teacher_id character varying(36) NOT NULL,
    code character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    semester character varying(50) NOT NULL,
    academic_year character varying(20),
    total_classes integer NOT NULL,
    period_duration integer NOT NULL,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    total_available_minutes integer GENERATED ALWAYS AS ((total_classes * period_duration)) STORED,
    CONSTRAINT check_course_date_order CHECK (((end_date IS NULL) OR (start_date IS NULL) OR (end_date >= start_date))),
    CONSTRAINT check_positive_period_duration CHECK ((period_duration > 0)),
    CONSTRAINT check_positive_total_classes CHECK ((total_classes > 0))
);

--
-- Name: lesson_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lesson_plans (
    id character varying(36) NOT NULL,
    session_id character varying(36) NOT NULL,
    topic_id character varying(36) NOT NULL,
    title character varying(255) NOT NULL,
    status character varying(50),
    mongo_doc_id character varying(100),
    ai_confidence double precision,
    teacher_overridden boolean,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    version integer DEFAULT 1 NOT NULL,
    CONSTRAINT check_ai_confidence_range CHECK (((ai_confidence >= (0.0)::double precision) AND (ai_confidence <= (1.0)::double precision))),
    CONSTRAINT check_lesson_plan_status CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'approved'::character varying, 'rejected'::character varying, 'modified'::character varying, 'completed'::character varying])::text[]))),
    CONSTRAINT check_lesson_plan_version_positive CHECK ((version >= 1))
);

--
-- Name: method_effectiveness; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.method_effectiveness (
    id character varying(36) NOT NULL,
    method_id character varying(36) NOT NULL,
    concept_type character varying(50) NOT NULL,
    baseline_score double precision,
    post_score double precision,
    observed_gain double precision,
    sample_sessions_count integer,
    updated_at timestamp without time zone,
    CONSTRAINT check_non_negative_sample_sessions CHECK ((sample_sessions_count >= 0))
);

--
-- Name: performance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.performance (
    id character varying(36) NOT NULL,
    concept_id character varying(36) NOT NULL,
    assessment_id character varying(36) NOT NULL,
    average_score double precision NOT NULL,
    sample_size integer,
    weakness_flag boolean,
    common_errors text,
    recorded_at timestamp without time zone,
    CONSTRAINT check_average_score_range CHECK (((average_score >= (0.0)::double precision) AND (average_score <= (100.0)::double precision))),
    CONSTRAINT check_positive_sample_size CHECK ((sample_size > 0))
);

--
-- Name: prerequisites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prerequisites (
    concept_id character varying(36) NOT NULL,
    prerequisite_id character varying(36) NOT NULL,
    CONSTRAINT check_no_self_prerequisite CHECK (((concept_id)::text <> (prerequisite_id)::text))
);

--
-- Name: teacher_constraints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher_constraints (
    id character varying(36) NOT NULL,
    course_id character varying(36) NOT NULL,
    max_lecture_ratio double precision,
    min_practice_ratio double precision,
    revision_threshold_score double precision,
    default_revision_minutes integer,
    created_at timestamp without time zone,
    CONSTRAINT check_max_lecture_ratio_range CHECK (((max_lecture_ratio >= (0.0)::double precision) AND (max_lecture_ratio <= (1.0)::double precision))),
    CONSTRAINT check_min_practice_ratio_range CHECK (((min_practice_ratio >= (0.0)::double precision) AND (min_practice_ratio <= (1.0)::double precision))),
    CONSTRAINT check_non_negative_revision_minutes CHECK ((default_revision_minutes >= 0)),
    CONSTRAINT check_revision_threshold_range CHECK (((revision_threshold_score >= (0.0)::double precision) AND (revision_threshold_score <= (100.0)::double precision)))
);

--
-- Name: teaching_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teaching_sessions (
    id character varying(36) NOT NULL,
    session_id character varying(36) NOT NULL,
    method_id character varying(36),
    actual_minutes integer NOT NULL,
    teacher_notes text,
    student_engagement_rating integer,
    completion_rate double precision,
    conducted_at timestamp without time zone,
    CONSTRAINT check_completion_rate_range CHECK (((completion_rate >= (0.0)::double precision) AND (completion_rate <= (1.0)::double precision))),
    CONSTRAINT check_engagement_rating_range CHECK (((student_engagement_rating >= 1) AND (student_engagement_rating <= 5))),
    CONSTRAINT check_positive_actual_minutes CHECK ((actual_minutes > 0))
);

--
-- Name: topics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topics (
    id character varying(36) NOT NULL,
    unit_id character varying(36) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    order_index integer NOT NULL,
    estimated_minutes integer,
    allocated_minutes integer,
    priority_score double precision,
    status character varying(50),
    CONSTRAINT check_non_negative_allocated_minutes CHECK ((allocated_minutes >= 0)),
    CONSTRAINT check_positive_estimated_minutes CHECK ((estimated_minutes > 0)),
    CONSTRAINT check_topic_status CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying])::text[])))
);

--
-- Name: units; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.units (
    id character varying(36) NOT NULL,
    course_id character varying(36) NOT NULL,
    unit_number integer NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    order_index integer NOT NULL,
    CONSTRAINT check_unit_number_positive CHECK ((unit_number >= 1))
);

--
-- Name: v_concept_mastery; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_concept_mastery WITH (security_invoker='true') AS
 SELECT u.course_id,
    u.unit_number,
    t.id AS topic_id,
    t.title AS topic_title,
    c.id AS concept_id,
    c.name AS concept_name,
    c.difficulty,
    c.importance,
    c.concept_type,
    COALESCE(ps.assessments_count, (0)::bigint) AS assessments_count,
    ps.avg_score,
    ps.latest_score,
    ps.previous_score,
    (ps.latest_score - ps.previous_score) AS score_trend,
    ds.downstream_count,
        CASE
            WHEN (ps.avg_score IS NULL) THEN 'not_assessed'::text
            WHEN (((ps.avg_score)::double precision < COALESCE(tc.revision_threshold_score, (60.0)::double precision)) AND (ds.downstream_count >= 2)) THEN 'bottleneck'::text
            WHEN ((ps.avg_score)::double precision < COALESCE(tc.revision_threshold_score, (60.0)::double precision)) THEN 'weak'::text
            WHEN (ps.avg_score < 70.0) THEN 'moderate'::text
            ELSE 'strong'::text
        END AS mastery_status
   FROM (((((public.concepts c
     JOIN public.topics t ON (((t.id)::text = (c.topic_id)::text)))
     JOIN public.units u ON (((u.id)::text = (t.unit_id)::text)))
     LEFT JOIN public.teacher_constraints tc ON (((tc.course_id)::text = (u.course_id)::text)))
     LEFT JOIN LATERAL ( SELECT count(*) AS assessments_count,
            round((avg(p.average_score))::numeric, 1) AS avg_score,
            (array_agg(p.average_score ORDER BY p.recorded_at DESC))[1] AS latest_score,
            (array_agg(p.average_score ORDER BY p.recorded_at DESC))[2] AS previous_score
           FROM public.performance p
          WHERE ((p.concept_id)::text = (c.id)::text)
         HAVING (count(*) > 0)) ps ON (true))
     LEFT JOIN LATERAL ( WITH RECURSIVE downstream(cid) AS (
                 SELECT p.concept_id
                   FROM public.prerequisites p
                  WHERE ((p.prerequisite_id)::text = (c.id)::text)
                UNION
                 SELECT p.concept_id
                   FROM (public.prerequisites p
                     JOIN downstream d ON (((p.prerequisite_id)::text = (d.cid)::text)))
                )
         SELECT count(*) AS downstream_count
           FROM downstream) ds ON (true));

--
-- Name: v_course_progress; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_course_progress WITH (security_invoker='true') AS
 SELECT c.id AS course_id,
    c.code,
    c.title,
    c.total_classes,
    c.total_available_minutes,
    tp.total_topics,
    tp.completed_topics,
    tp.in_progress_topics,
    round(((100.0 * (tp.completed_topics)::numeric) / (NULLIF(tp.total_topics, 0))::numeric), 1) AS topic_completion_pct,
    sp.completed_sessions,
    sp.scheduled_sessions,
    sp.cancelled_sessions,
    round(((100.0 * (sp.completed_sessions)::numeric) / (c.total_classes)::numeric), 1) AS session_completion_pct,
    COALESCE(tm.taught_minutes, (0)::bigint) AS taught_minutes,
    (c.total_available_minutes - COALESCE(tm.taught_minutes, (0)::bigint)) AS remaining_minutes
   FROM (((public.courses c
     LEFT JOIN LATERAL ( SELECT count(*) AS total_topics,
            count(*) FILTER (WHERE ((t.status)::text = 'completed'::text)) AS completed_topics,
            count(*) FILTER (WHERE ((t.status)::text = 'in_progress'::text)) AS in_progress_topics
           FROM (public.topics t
             JOIN public.units u ON (((u.id)::text = (t.unit_id)::text)))
          WHERE ((u.course_id)::text = (c.id)::text)) tp ON (true))
     LEFT JOIN LATERAL ( SELECT count(*) FILTER (WHERE ((cs.status)::text = 'completed'::text)) AS completed_sessions,
            count(*) FILTER (WHERE ((cs.status)::text = 'scheduled'::text)) AS scheduled_sessions,
            count(*) FILTER (WHERE ((cs.status)::text = 'cancelled'::text)) AS cancelled_sessions
           FROM public.class_sessions cs
          WHERE ((cs.course_id)::text = (c.id)::text)) sp ON (true))
     LEFT JOIN LATERAL ( SELECT sum(ts.actual_minutes) AS taught_minutes
           FROM (public.teaching_sessions ts
             JOIN public.class_sessions cs ON (((cs.id)::text = (ts.session_id)::text)))
          WHERE ((cs.course_id)::text = (c.id)::text)) tm ON (true));

--
-- Name: mv_course_dashboard; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.mv_course_dashboard AS
 SELECT vp.course_id,
    vp.code,
    vp.title,
    vp.total_classes,
    vp.total_available_minutes,
    vp.total_topics,
    vp.completed_topics,
    vp.in_progress_topics,
    vp.topic_completion_pct,
    vp.completed_sessions,
    vp.scheduled_sessions,
    vp.cancelled_sessions,
    vp.session_completion_pct,
    vp.taught_minutes,
    vp.remaining_minutes,
    cm.strong_concepts,
    cm.moderate_concepts,
    cm.weak_concepts,
    cm.bottleneck_concepts,
    cm.not_assessed_concepts,
    tp.remaining_topics,
    tp.remaining_periods,
    tp.pressure_ratio,
    tp.pressure_status,
    timezone('utc'::text, now()) AS refreshed_at
   FROM ((public.v_course_progress vp
     LEFT JOIN LATERAL ( SELECT count(*) FILTER (WHERE (m.mastery_status = 'strong'::text)) AS strong_concepts,
            count(*) FILTER (WHERE (m.mastery_status = 'moderate'::text)) AS moderate_concepts,
            count(*) FILTER (WHERE (m.mastery_status = 'weak'::text)) AS weak_concepts,
            count(*) FILTER (WHERE (m.mastery_status = 'bottleneck'::text)) AS bottleneck_concepts,
            count(*) FILTER (WHERE (m.mastery_status = 'not_assessed'::text)) AS not_assessed_concepts
           FROM public.v_concept_mastery m
          WHERE ((m.course_id)::text = (vp.course_id)::text)) cm ON (true))
     LEFT JOIN LATERAL public.fn_time_pressure(vp.course_id) tp(remaining_topics, remaining_periods, remaining_required_minutes, remaining_available_minutes, pressure_ratio, pressure_status) ON (true))
  WITH NO DATA;

--
-- Name: question_concepts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.question_concepts (
    question_id character varying(36) NOT NULL,
    concept_id character varying(36) NOT NULL,
    weightage double precision,
    CONSTRAINT check_positive_weightage CHECK ((weightage > (0)::double precision))
);

--
-- Name: questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.questions (
    id character varying(36) NOT NULL,
    assessment_id character varying(36) NOT NULL,
    question_number integer NOT NULL,
    max_marks double precision NOT NULL,
    text text NOT NULL,
    CONSTRAINT check_positive_question_marks CHECK ((max_marks > (0)::double precision)),
    CONSTRAINT check_positive_question_number CHECK ((question_number >= 1))
);

--
-- Name: sections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sections (
    id character varying(36) NOT NULL,
    course_id character varying(36) NOT NULL,
    name character varying(50) NOT NULL,
    room_number character varying(50),
    student_count integer,
    CONSTRAINT check_positive_student_count CHECK ((student_count > 0))
);

--
-- Name: teacher_preferred_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher_preferred_methods (
    constraint_id character varying(36) NOT NULL,
    method_id character varying(36) NOT NULL,
    rank integer NOT NULL,
    CONSTRAINT check_positive_preference_rank CHECK ((rank >= 1))
);

--
-- Name: teachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teachers (
    id character varying(36) NOT NULL,
    user_id character varying(36) NOT NULL,
    department character varying(100) NOT NULL,
    designation character varying(100),
    employee_id character varying(50) NOT NULL,
    office_location character varying(100)
);

--
-- Name: teaching_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teaching_methods (
    id character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    category character varying(50) NOT NULL,
    description text,
    typical_time_ratio double precision,
    CONSTRAINT check_typical_time_ratio_range CHECK (((typical_time_ratio > (0.0)::double precision) AND (typical_time_ratio <= (1.0)::double precision)))
);

--
-- Name: txn_lab_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.txn_lab_accounts (
    id character varying(20) NOT NULL,
    label character varying(50) NOT NULL,
    balance integer NOT NULL,
    CONSTRAINT check_non_negative_balance CHECK ((balance >= 0))
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id character varying(36) NOT NULL,
    email character varying(255) NOT NULL,
    hashed_password character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    role character varying(50) NOT NULL,
    is_active boolean,
    created_at timestamp without time zone,
    CONSTRAINT check_user_role CHECK (((role)::text = ANY ((ARRAY['teacher'::character varying, 'admin'::character varying])::text[])))
);

--
-- Name: v_teaching_history; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_teaching_history WITH (security_invoker='true') AS
 SELECT cs.course_id,
    cs.session_number,
    cs.scheduled_date,
    t.title AS topic_title,
    tm.name AS method_name,
    tm.category AS method_category,
    ts.actual_minutes,
    ts.student_engagement_rating,
    ts.completion_rate,
    ts.teacher_notes,
    ts.conducted_at
   FROM (((public.teaching_sessions ts
     JOIN public.class_sessions cs ON (((cs.id)::text = (ts.session_id)::text)))
     LEFT JOIN public.topics t ON (((t.id)::text = (cs.current_topic_id)::text)))
     LEFT JOIN public.teaching_methods tm ON (((tm.id)::text = (ts.method_id)::text)));

--
-- Name: audit_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log ALTER COLUMN id SET DEFAULT nextval('public.audit_log_id_seq'::regclass);

--
-- Name: assessments assessments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessments
    ADD CONSTRAINT assessments_pkey PRIMARY KEY (id);

--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

--
-- Name: class_sessions class_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_sessions
    ADD CONSTRAINT class_sessions_pkey PRIMARY KEY (id);

--
-- Name: concept_outcomes concept_outcomes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concept_outcomes
    ADD CONSTRAINT concept_outcomes_pkey PRIMARY KEY (concept_id, outcome_id);

--
-- Name: concepts concepts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concepts
    ADD CONSTRAINT concepts_pkey PRIMARY KEY (id);

--
-- Name: course_outcomes course_outcomes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_outcomes
    ADD CONSTRAINT course_outcomes_pkey PRIMARY KEY (id);

--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);

--
-- Name: lesson_plans lesson_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lesson_plans
    ADD CONSTRAINT lesson_plans_pkey PRIMARY KEY (id);

--
-- Name: lesson_plans lesson_plans_session_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lesson_plans
    ADD CONSTRAINT lesson_plans_session_id_key UNIQUE (session_id);

--
-- Name: method_effectiveness method_effectiveness_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.method_effectiveness
    ADD CONSTRAINT method_effectiveness_pkey PRIMARY KEY (id);

--
-- Name: performance performance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.performance
    ADD CONSTRAINT performance_pkey PRIMARY KEY (id);

--
-- Name: prerequisites prerequisites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prerequisites
    ADD CONSTRAINT prerequisites_pkey PRIMARY KEY (concept_id, prerequisite_id);

--
-- Name: question_concepts question_concepts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question_concepts
    ADD CONSTRAINT question_concepts_pkey PRIMARY KEY (question_id, concept_id);

--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);

--
-- Name: sections sections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_pkey PRIMARY KEY (id);

--
-- Name: teacher_constraints teacher_constraints_course_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_constraints
    ADD CONSTRAINT teacher_constraints_course_id_key UNIQUE (course_id);

--
-- Name: teacher_constraints teacher_constraints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_constraints
    ADD CONSTRAINT teacher_constraints_pkey PRIMARY KEY (id);

--
-- Name: teacher_preferred_methods teacher_preferred_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_preferred_methods
    ADD CONSTRAINT teacher_preferred_methods_pkey PRIMARY KEY (constraint_id, method_id);

--
-- Name: teachers teachers_employee_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_employee_id_key UNIQUE (employee_id);

--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);

--
-- Name: teachers teachers_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_user_id_key UNIQUE (user_id);

--
-- Name: teaching_methods teaching_methods_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teaching_methods
    ADD CONSTRAINT teaching_methods_name_key UNIQUE (name);

--
-- Name: teaching_methods teaching_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teaching_methods
    ADD CONSTRAINT teaching_methods_pkey PRIMARY KEY (id);

--
-- Name: teaching_sessions teaching_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teaching_sessions
    ADD CONSTRAINT teaching_sessions_pkey PRIMARY KEY (id);

--
-- Name: teaching_sessions teaching_sessions_session_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teaching_sessions
    ADD CONSTRAINT teaching_sessions_session_id_key UNIQUE (session_id);

--
-- Name: topics topics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY (id);

--
-- Name: txn_lab_accounts txn_lab_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.txn_lab_accounts
    ADD CONSTRAINT txn_lab_accounts_pkey PRIMARY KEY (id);

--
-- Name: units units_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_pkey PRIMARY KEY (id);

--
-- Name: questions uq_assessment_question_num; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT uq_assessment_question_num UNIQUE (assessment_id, question_number);

--
-- Name: performance uq_concept_assessment_performance; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.performance
    ADD CONSTRAINT uq_concept_assessment_performance UNIQUE (concept_id, assessment_id);

--
-- Name: course_outcomes uq_course_outcome_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_outcomes
    ADD CONSTRAINT uq_course_outcome_code UNIQUE (course_id, code);

--
-- Name: sections uq_course_section_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT uq_course_section_name UNIQUE (course_id, name);

--
-- Name: class_sessions uq_course_session_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_sessions
    ADD CONSTRAINT uq_course_session_number UNIQUE (course_id, session_number);

--
-- Name: units uq_course_unit_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT uq_course_unit_number UNIQUE (course_id, unit_number);

--
-- Name: teacher_preferred_methods uq_preferred_method_rank; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_preferred_methods
    ADD CONSTRAINT uq_preferred_method_rank UNIQUE (constraint_id, rank);

--
-- Name: courses uq_teacher_course_semester; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT uq_teacher_course_semester UNIQUE (teacher_id, code, semester);

--
-- Name: topics uq_unit_topic_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT uq_unit_topic_order UNIQUE (unit_id, order_index);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: ix_assessments_course_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_assessments_course_id ON public.assessments USING btree (course_id);

--
-- Name: ix_assessments_scheduled_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_assessments_scheduled_date ON public.assessments USING btree (scheduled_date);

--
-- Name: ix_audit_log_table_row; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_audit_log_table_row ON public.audit_log USING btree (table_name, row_id, changed_at);

--
-- Name: ix_class_sessions_course_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_class_sessions_course_id ON public.class_sessions USING btree (course_id);

--
-- Name: ix_class_sessions_current_topic; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_class_sessions_current_topic ON public.class_sessions USING btree (current_topic_id);

--
-- Name: ix_class_sessions_upcoming; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_class_sessions_upcoming ON public.class_sessions USING btree (course_id, session_number) WHERE ((status)::text = 'scheduled'::text);

--
-- Name: ix_concept_outcomes_outcome; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_concept_outcomes_outcome ON public.concept_outcomes USING btree (outcome_id);

--
-- Name: ix_concepts_topic_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_concepts_topic_id ON public.concepts USING btree (topic_id);

--
-- Name: ix_course_outcomes_course_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_course_outcomes_course_id ON public.course_outcomes USING btree (course_id);

--
-- Name: ix_courses_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_courses_code ON public.courses USING btree (code);

--
-- Name: ix_courses_teacher_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_courses_teacher_id ON public.courses USING btree (teacher_id);

--
-- Name: ix_lesson_plans_topic_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_lesson_plans_topic_id ON public.lesson_plans USING btree (topic_id);

--
-- Name: ix_method_effectiveness_method_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_method_effectiveness_method_id ON public.method_effectiveness USING btree (method_id);

--
-- Name: ix_performance_assessment_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_performance_assessment_id ON public.performance USING btree (assessment_id);

--
-- Name: ix_performance_concept_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_performance_concept_id ON public.performance USING btree (concept_id);

--
-- Name: ix_performance_weak; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_performance_weak ON public.performance USING btree (concept_id) WHERE weakness_flag;

--
-- Name: ix_prerequisites_prerequisite; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_prerequisites_prerequisite ON public.prerequisites USING btree (prerequisite_id);

--
-- Name: ix_question_concepts_concept; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_question_concepts_concept ON public.question_concepts USING btree (concept_id);

--
-- Name: ix_questions_assessment_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_questions_assessment_id ON public.questions USING btree (assessment_id);

--
-- Name: ix_sections_course_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sections_course_id ON public.sections USING btree (course_id);

--
-- Name: ix_teacher_preferred_methods_method; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_teacher_preferred_methods_method ON public.teacher_preferred_methods USING btree (method_id);

--
-- Name: ix_topics_unit_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_topics_unit_id ON public.topics USING btree (unit_id);

--
-- Name: ix_units_course_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_units_course_id ON public.units USING btree (course_id);

--
-- Name: ix_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_users_email ON public.users USING btree (email);

--
-- Name: ux_mv_course_dashboard_course; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_mv_course_dashboard_course ON public.mv_course_dashboard USING btree (course_id);

--
-- Name: assessments trg_assessments_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_assessments_audit AFTER INSERT OR DELETE OR UPDATE ON public.assessments FOR EACH ROW EXECUTE FUNCTION public.fn_audit_row_change();

--
-- Name: class_sessions trg_class_sessions_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_class_sessions_audit AFTER INSERT OR DELETE OR UPDATE ON public.class_sessions FOR EACH ROW EXECUTE FUNCTION public.fn_audit_row_change();

--
-- Name: concepts trg_concepts_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_concepts_audit AFTER INSERT OR DELETE OR UPDATE ON public.concepts FOR EACH ROW EXECUTE FUNCTION public.fn_audit_row_change();

--
-- Name: courses trg_courses_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_courses_audit AFTER INSERT OR DELETE OR UPDATE ON public.courses FOR EACH ROW EXECUTE FUNCTION public.fn_audit_row_change();

--
-- Name: courses trg_courses_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_courses_updated_at BEFORE UPDATE ON public.courses FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

--
-- Name: lesson_plans trg_lesson_plans_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_lesson_plans_audit AFTER INSERT OR DELETE OR UPDATE ON public.lesson_plans FOR EACH ROW EXECUTE FUNCTION public.fn_audit_row_change();

--
-- Name: lesson_plans trg_lesson_plans_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_lesson_plans_updated_at BEFORE UPDATE ON public.lesson_plans FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

--
-- Name: method_effectiveness trg_method_effectiveness_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_method_effectiveness_updated_at BEFORE UPDATE ON public.method_effectiveness FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

--
-- Name: performance trg_performance_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_performance_audit AFTER INSERT OR DELETE OR UPDATE ON public.performance FOR EACH ROW EXECUTE FUNCTION public.fn_audit_row_change();

--
-- Name: performance trg_performance_weakness; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_performance_weakness BEFORE INSERT OR UPDATE OF average_score, assessment_id ON public.performance FOR EACH ROW EXECUTE FUNCTION public.fn_performance_weakness();

--
-- Name: prerequisites trg_prerequisite_guard; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_prerequisite_guard BEFORE INSERT OR UPDATE ON public.prerequisites FOR EACH ROW EXECUTE FUNCTION public.fn_prerequisite_guard();

--
-- Name: teacher_constraints trg_teacher_constraints_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_teacher_constraints_audit AFTER INSERT OR DELETE OR UPDATE ON public.teacher_constraints FOR EACH ROW EXECUTE FUNCTION public.fn_audit_row_change();

--
-- Name: teaching_sessions trg_teaching_sessions_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_teaching_sessions_audit AFTER INSERT OR DELETE OR UPDATE ON public.teaching_sessions FOR EACH ROW EXECUTE FUNCTION public.fn_audit_row_change();

--
-- Name: teacher_constraints trg_threshold_recompute_weakness; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_threshold_recompute_weakness AFTER UPDATE OF revision_threshold_score ON public.teacher_constraints FOR EACH ROW EXECUTE FUNCTION public.fn_threshold_recompute_weakness();

--
-- Name: topics trg_topics_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_topics_audit AFTER INSERT OR DELETE OR UPDATE ON public.topics FOR EACH ROW EXECUTE FUNCTION public.fn_audit_row_change();

--
-- Name: units trg_units_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_units_audit AFTER INSERT OR DELETE OR UPDATE ON public.units FOR EACH ROW EXECUTE FUNCTION public.fn_audit_row_change();

--
-- Name: assessments assessments_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessments
    ADD CONSTRAINT assessments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;

--
-- Name: class_sessions class_sessions_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_sessions
    ADD CONSTRAINT class_sessions_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;

--
-- Name: class_sessions class_sessions_current_topic_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_sessions
    ADD CONSTRAINT class_sessions_current_topic_id_fkey FOREIGN KEY (current_topic_id) REFERENCES public.topics(id) ON DELETE SET NULL;

--
-- Name: concept_outcomes concept_outcomes_concept_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concept_outcomes
    ADD CONSTRAINT concept_outcomes_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id) ON DELETE CASCADE;

--
-- Name: concept_outcomes concept_outcomes_outcome_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concept_outcomes
    ADD CONSTRAINT concept_outcomes_outcome_id_fkey FOREIGN KEY (outcome_id) REFERENCES public.course_outcomes(id) ON DELETE CASCADE;

--
-- Name: concepts concepts_topic_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concepts
    ADD CONSTRAINT concepts_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;

--
-- Name: course_outcomes course_outcomes_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_outcomes
    ADD CONSTRAINT course_outcomes_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;

--
-- Name: courses courses_teacher_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id) ON DELETE CASCADE;

--
-- Name: lesson_plans lesson_plans_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lesson_plans
    ADD CONSTRAINT lesson_plans_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.class_sessions(id) ON DELETE CASCADE;

--
-- Name: lesson_plans lesson_plans_topic_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lesson_plans
    ADD CONSTRAINT lesson_plans_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;

--
-- Name: method_effectiveness method_effectiveness_method_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.method_effectiveness
    ADD CONSTRAINT method_effectiveness_method_id_fkey FOREIGN KEY (method_id) REFERENCES public.teaching_methods(id) ON DELETE CASCADE;

--
-- Name: performance performance_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.performance
    ADD CONSTRAINT performance_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id) ON DELETE CASCADE;

--
-- Name: performance performance_concept_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.performance
    ADD CONSTRAINT performance_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id) ON DELETE CASCADE;

--
-- Name: prerequisites prerequisites_concept_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prerequisites
    ADD CONSTRAINT prerequisites_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id) ON DELETE CASCADE;

--
-- Name: prerequisites prerequisites_prerequisite_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prerequisites
    ADD CONSTRAINT prerequisites_prerequisite_id_fkey FOREIGN KEY (prerequisite_id) REFERENCES public.concepts(id) ON DELETE CASCADE;

--
-- Name: question_concepts question_concepts_concept_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question_concepts
    ADD CONSTRAINT question_concepts_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id) ON DELETE CASCADE;

--
-- Name: question_concepts question_concepts_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question_concepts
    ADD CONSTRAINT question_concepts_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE;

--
-- Name: questions questions_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id) ON DELETE CASCADE;

--
-- Name: sections sections_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;

--
-- Name: teacher_constraints teacher_constraints_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_constraints
    ADD CONSTRAINT teacher_constraints_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;

--
-- Name: teacher_preferred_methods teacher_preferred_methods_constraint_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_preferred_methods
    ADD CONSTRAINT teacher_preferred_methods_constraint_id_fkey FOREIGN KEY (constraint_id) REFERENCES public.teacher_constraints(id) ON DELETE CASCADE;

--
-- Name: teacher_preferred_methods teacher_preferred_methods_method_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_preferred_methods
    ADD CONSTRAINT teacher_preferred_methods_method_id_fkey FOREIGN KEY (method_id) REFERENCES public.teaching_methods(id) ON DELETE CASCADE;

--
-- Name: teachers teachers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: teaching_sessions teaching_sessions_method_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teaching_sessions
    ADD CONSTRAINT teaching_sessions_method_id_fkey FOREIGN KEY (method_id) REFERENCES public.teaching_methods(id) ON DELETE SET NULL;

--
-- Name: teaching_sessions teaching_sessions_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teaching_sessions
    ADD CONSTRAINT teaching_sessions_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.class_sessions(id) ON DELETE CASCADE;

--
-- Name: topics topics_unit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id) ON DELETE CASCADE;

--
-- Name: units units_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;

--
-- Name: assessments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;

--
-- Name: audit_log; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

--
-- Name: class_sessions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.class_sessions ENABLE ROW LEVEL SECURITY;

--
-- Name: concept_outcomes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.concept_outcomes ENABLE ROW LEVEL SECURITY;

--
-- Name: concepts; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.concepts ENABLE ROW LEVEL SECURITY;

--
-- Name: assessments console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.assessments FOR SELECT TO optiteach_readonly USING (((course_id)::text IN ( SELECT courses.id
   FROM public.courses)));

--
-- Name: audit_log console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.audit_log FOR SELECT TO optiteach_readonly USING (((current_setting('app.is_admin'::text, true) = 'true'::text) OR ((COALESCE(new_data, old_data) ->> 'course_id'::text) IN ( SELECT courses.id
   FROM public.courses)) OR ((row_id)::text IN ( SELECT courses.id
   FROM public.courses))));

--
-- Name: class_sessions console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.class_sessions FOR SELECT TO optiteach_readonly USING (((course_id)::text IN ( SELECT courses.id
   FROM public.courses)));

--
-- Name: concept_outcomes console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.concept_outcomes FOR SELECT TO optiteach_readonly USING (((concept_id)::text IN ( SELECT concepts.id
   FROM public.concepts)));

--
-- Name: concepts console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.concepts FOR SELECT TO optiteach_readonly USING (((topic_id)::text IN ( SELECT topics.id
   FROM public.topics)));

--
-- Name: course_outcomes console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.course_outcomes FOR SELECT TO optiteach_readonly USING (((course_id)::text IN ( SELECT courses.id
   FROM public.courses)));

--
-- Name: courses console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.courses FOR SELECT TO optiteach_readonly USING (((current_setting('app.is_admin'::text, true) = 'true'::text) OR ((teacher_id)::text = current_setting('app.teacher_id'::text, true))));

--
-- Name: lesson_plans console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.lesson_plans FOR SELECT TO optiteach_readonly USING (((session_id)::text IN ( SELECT class_sessions.id
   FROM public.class_sessions)));

--
-- Name: performance console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.performance FOR SELECT TO optiteach_readonly USING (((assessment_id)::text IN ( SELECT assessments.id
   FROM public.assessments)));

--
-- Name: prerequisites console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.prerequisites FOR SELECT TO optiteach_readonly USING (((concept_id)::text IN ( SELECT concepts.id
   FROM public.concepts)));

--
-- Name: question_concepts console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.question_concepts FOR SELECT TO optiteach_readonly USING (((question_id)::text IN ( SELECT questions.id
   FROM public.questions)));

--
-- Name: questions console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.questions FOR SELECT TO optiteach_readonly USING (((assessment_id)::text IN ( SELECT assessments.id
   FROM public.assessments)));

--
-- Name: sections console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.sections FOR SELECT TO optiteach_readonly USING (((course_id)::text IN ( SELECT courses.id
   FROM public.courses)));

--
-- Name: teacher_constraints console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.teacher_constraints FOR SELECT TO optiteach_readonly USING (((course_id)::text IN ( SELECT courses.id
   FROM public.courses)));

--
-- Name: teacher_preferred_methods console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.teacher_preferred_methods FOR SELECT TO optiteach_readonly USING (((constraint_id)::text IN ( SELECT teacher_constraints.id
   FROM public.teacher_constraints)));

--
-- Name: teachers console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.teachers FOR SELECT TO optiteach_readonly USING (((current_setting('app.is_admin'::text, true) = 'true'::text) OR ((id)::text = current_setting('app.teacher_id'::text, true))));

--
-- Name: teaching_sessions console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.teaching_sessions FOR SELECT TO optiteach_readonly USING (((session_id)::text IN ( SELECT class_sessions.id
   FROM public.class_sessions)));

--
-- Name: topics console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.topics FOR SELECT TO optiteach_readonly USING (((unit_id)::text IN ( SELECT units.id
   FROM public.units)));

--
-- Name: units console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.units FOR SELECT TO optiteach_readonly USING (((course_id)::text IN ( SELECT courses.id
   FROM public.courses)));

--
-- Name: users console_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY console_read ON public.users FOR SELECT TO optiteach_readonly USING (((current_setting('app.is_admin'::text, true) = 'true'::text) OR ((id)::text IN ( SELECT teachers.user_id
   FROM public.teachers))));

--
-- Name: course_outcomes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.course_outcomes ENABLE ROW LEVEL SECURITY;

--
-- Name: courses; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

--
-- Name: lesson_plans; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.lesson_plans ENABLE ROW LEVEL SECURITY;

--
-- Name: performance; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.performance ENABLE ROW LEVEL SECURITY;

--
-- Name: prerequisites; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.prerequisites ENABLE ROW LEVEL SECURITY;

--
-- Name: question_concepts; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.question_concepts ENABLE ROW LEVEL SECURITY;

--
-- Name: questions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

--
-- Name: sections; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.sections ENABLE ROW LEVEL SECURITY;

--
-- Name: teacher_constraints; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.teacher_constraints ENABLE ROW LEVEL SECURITY;

--
-- Name: teacher_preferred_methods; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.teacher_preferred_methods ENABLE ROW LEVEL SECURITY;

--
-- Name: teachers; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;

--
-- Name: teaching_sessions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.teaching_sessions ENABLE ROW LEVEL SECURITY;

--
-- Name: topics; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.topics ENABLE ROW LEVEL SECURITY;

--
-- Name: units; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;

--
-- Name: users; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

GRANT USAGE ON SCHEMA public TO optiteach_app;
GRANT USAGE ON SCHEMA public TO optiteach_readonly;

--
-- Name: FUNCTION query_to_xml(query text, nulls boolean, tableforest boolean, targetns text); Type: ACL; Schema: pg_catalog; Owner: -
--

REVOKE ALL ON FUNCTION pg_catalog.query_to_xml(query text, nulls boolean, tableforest boolean, targetns text) FROM PUBLIC;

--
-- Name: FUNCTION query_to_xml_and_xmlschema(query text, nulls boolean, tableforest boolean, targetns text); Type: ACL; Schema: pg_catalog; Owner: -
--

REVOKE ALL ON FUNCTION pg_catalog.query_to_xml_and_xmlschema(query text, nulls boolean, tableforest boolean, targetns text) FROM PUBLIC;

--
-- Name: FUNCTION query_to_xmlschema(query text, nulls boolean, tableforest boolean, targetns text); Type: ACL; Schema: pg_catalog; Owner: -
--

REVOKE ALL ON FUNCTION pg_catalog.query_to_xmlschema(query text, nulls boolean, tableforest boolean, targetns text) FROM PUBLIC;

--
-- Name: FUNCTION set_config(text, text, boolean); Type: ACL; Schema: pg_catalog; Owner: -
--

REVOKE ALL ON FUNCTION pg_catalog.set_config(text, text, boolean) FROM PUBLIC;
GRANT ALL ON FUNCTION pg_catalog.set_config(text, text, boolean) TO optiteach_app;

--
-- Name: FUNCTION fn_audit_row_change(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.fn_audit_row_change() FROM PUBLIC;

--
-- Name: FUNCTION fn_performance_weakness(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.fn_performance_weakness() FROM PUBLIC;

--
-- Name: FUNCTION fn_prerequisite_chain(p_concept_id character varying); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.fn_prerequisite_chain(p_concept_id character varying) FROM PUBLIC;
GRANT ALL ON FUNCTION public.fn_prerequisite_chain(p_concept_id character varying) TO optiteach_app;
GRANT ALL ON FUNCTION public.fn_prerequisite_chain(p_concept_id character varying) TO optiteach_readonly;

--
-- Name: FUNCTION fn_prerequisite_guard(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.fn_prerequisite_guard() FROM PUBLIC;

--
-- Name: FUNCTION fn_refresh_course_dashboard(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.fn_refresh_course_dashboard() FROM PUBLIC;
GRANT ALL ON FUNCTION public.fn_refresh_course_dashboard() TO optiteach_app;

--
-- Name: FUNCTION fn_set_updated_at(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.fn_set_updated_at() FROM PUBLIC;

--
-- Name: FUNCTION fn_threshold_recompute_weakness(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.fn_threshold_recompute_weakness() FROM PUBLIC;

--
-- Name: FUNCTION fn_time_pressure(p_course_id character varying); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.fn_time_pressure(p_course_id character varying) FROM PUBLIC;
GRANT ALL ON FUNCTION public.fn_time_pressure(p_course_id character varying) TO optiteach_app;
GRANT ALL ON FUNCTION public.fn_time_pressure(p_course_id character varying) TO optiteach_readonly;

--
-- Name: PROCEDURE sp_record_concept_performance(IN p_assessment_id character varying, IN p_concept_id character varying, IN p_average_score double precision, IN p_sample_size integer, IN p_common_errors text); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON PROCEDURE public.sp_record_concept_performance(IN p_assessment_id character varying, IN p_concept_id character varying, IN p_average_score double precision, IN p_sample_size integer, IN p_common_errors text) FROM PUBLIC;
GRANT ALL ON PROCEDURE public.sp_record_concept_performance(IN p_assessment_id character varying, IN p_concept_id character varying, IN p_average_score double precision, IN p_sample_size integer, IN p_common_errors text) TO optiteach_app;

--
-- Name: TABLE assessments; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.assessments TO optiteach_app;
GRANT SELECT ON TABLE public.assessments TO optiteach_readonly;

--
-- Name: TABLE audit_log; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT ON TABLE public.audit_log TO optiteach_app;
GRANT SELECT ON TABLE public.audit_log TO optiteach_readonly;

--
-- Name: TABLE class_sessions; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.class_sessions TO optiteach_app;
GRANT SELECT ON TABLE public.class_sessions TO optiteach_readonly;

--
-- Name: TABLE concept_outcomes; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.concept_outcomes TO optiteach_app;
GRANT SELECT ON TABLE public.concept_outcomes TO optiteach_readonly;

--
-- Name: TABLE concepts; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.concepts TO optiteach_app;
GRANT SELECT ON TABLE public.concepts TO optiteach_readonly;

--
-- Name: TABLE course_outcomes; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.course_outcomes TO optiteach_app;
GRANT SELECT ON TABLE public.course_outcomes TO optiteach_readonly;

--
-- Name: TABLE courses; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.courses TO optiteach_app;
GRANT SELECT ON TABLE public.courses TO optiteach_readonly;

--
-- Name: TABLE lesson_plans; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.lesson_plans TO optiteach_app;
GRANT SELECT ON TABLE public.lesson_plans TO optiteach_readonly;

--
-- Name: TABLE method_effectiveness; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.method_effectiveness TO optiteach_app;
GRANT SELECT ON TABLE public.method_effectiveness TO optiteach_readonly;

--
-- Name: TABLE performance; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.performance TO optiteach_app;
GRANT SELECT ON TABLE public.performance TO optiteach_readonly;

--
-- Name: TABLE prerequisites; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.prerequisites TO optiteach_app;
GRANT SELECT ON TABLE public.prerequisites TO optiteach_readonly;

--
-- Name: TABLE teacher_constraints; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.teacher_constraints TO optiteach_app;
GRANT SELECT ON TABLE public.teacher_constraints TO optiteach_readonly;

--
-- Name: TABLE teaching_sessions; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.teaching_sessions TO optiteach_app;
GRANT SELECT ON TABLE public.teaching_sessions TO optiteach_readonly;

--
-- Name: TABLE topics; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.topics TO optiteach_app;
GRANT SELECT ON TABLE public.topics TO optiteach_readonly;

--
-- Name: TABLE units; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.units TO optiteach_app;
GRANT SELECT ON TABLE public.units TO optiteach_readonly;

--
-- Name: TABLE v_concept_mastery; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.v_concept_mastery TO optiteach_app;
GRANT SELECT ON TABLE public.v_concept_mastery TO optiteach_readonly;

--
-- Name: TABLE v_course_progress; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.v_course_progress TO optiteach_app;
GRANT SELECT ON TABLE public.v_course_progress TO optiteach_readonly;

--
-- Name: TABLE mv_course_dashboard; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.mv_course_dashboard TO optiteach_app;

--
-- Name: TABLE question_concepts; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.question_concepts TO optiteach_app;
GRANT SELECT ON TABLE public.question_concepts TO optiteach_readonly;

--
-- Name: TABLE questions; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.questions TO optiteach_app;
GRANT SELECT ON TABLE public.questions TO optiteach_readonly;

--
-- Name: TABLE sections; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.sections TO optiteach_app;
GRANT SELECT ON TABLE public.sections TO optiteach_readonly;

--
-- Name: TABLE teacher_preferred_methods; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.teacher_preferred_methods TO optiteach_app;
GRANT SELECT ON TABLE public.teacher_preferred_methods TO optiteach_readonly;

--
-- Name: TABLE teachers; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.teachers TO optiteach_app;
GRANT SELECT ON TABLE public.teachers TO optiteach_readonly;

--
-- Name: TABLE teaching_methods; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.teaching_methods TO optiteach_app;
GRANT SELECT ON TABLE public.teaching_methods TO optiteach_readonly;

--
-- Name: TABLE txn_lab_accounts; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.txn_lab_accounts TO optiteach_app;

--
-- Name: TABLE users; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.users TO optiteach_app;

--
-- Name: COLUMN users.id; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(id) ON TABLE public.users TO optiteach_readonly;

--
-- Name: COLUMN users.email; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(email) ON TABLE public.users TO optiteach_readonly;

--
-- Name: COLUMN users.full_name; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(full_name) ON TABLE public.users TO optiteach_readonly;

--
-- Name: COLUMN users.role; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(role) ON TABLE public.users TO optiteach_readonly;

--
-- Name: COLUMN users.is_active; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(is_active) ON TABLE public.users TO optiteach_readonly;

--
-- Name: COLUMN users.created_at; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT(created_at) ON TABLE public.users TO optiteach_readonly;

--
-- Name: TABLE v_teaching_history; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.v_teaching_history TO optiteach_app;
GRANT SELECT ON TABLE public.v_teaching_history TO optiteach_readonly;

--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO optiteach_app;

--
-- PostgreSQL database dump complete
--
