-- ===================================================================
-- OptiTeach: SQL demonstration queries (as run by the DBMS Insights page)
--
-- GENERATED by database/scripts/export_sql_reference.py from
-- backend/app/services/dbms_insights_service.py - regenerate, don't edit.
-- :course_id is a bound parameter; queries marked [PostgreSQL] use
-- server-side objects created in migration 0002.
-- ===================================================================

-- 1. Topics Remaining in Curriculum
-- Retrieves all uncompleted topics ordered by unit and curricular sequence.
-- Features: INNER JOIN, Filtering
SELECT u.unit_number, u.title AS unit_title, t.title AS topic_title, 
       t.estimated_minutes, t.allocated_minutes, t.priority_score, t.status
FROM topics t
JOIN units u ON t.unit_id = u.id
WHERE u.course_id = :course_id AND t.status != 'completed'
ORDER BY u.unit_number, t.order_index;

-- 2. Contact Time Utilization & Remaining Budget
-- Calculates total planned teaching minutes versus recorded taught minutes.
-- Features: LEFT JOIN, COALESCE, GROUP BY
SELECT c.code, c.title, c.total_available_minutes,
       COALESCE(SUM(ts.actual_minutes), 0) AS actual_taught_minutes,
       (c.total_available_minutes - COALESCE(SUM(ts.actual_minutes), 0)) AS remaining_teaching_minutes
FROM courses c
LEFT JOIN class_sessions cs ON cs.course_id = c.id
LEFT JOIN teaching_sessions ts ON ts.session_id = cs.id
WHERE c.id = :course_id
GROUP BY c.id, c.code, c.title, c.total_available_minutes;

-- 3. Below-Threshold Concepts (Weakness Detection)
-- Identifies concepts where student cohort score falls below the 60% threshold.
-- Features: GROUP BY, HAVING, Aggregates
SELECT c.name AS concept_name, c.difficulty, c.importance, 
       ROUND(AVG(p.average_score)::numeric, 1) AS avg_score,
       COUNT(p.id) AS assessment_count,
       MAX(p.common_errors) AS primary_misconception
FROM concepts c
JOIN performance p ON p.concept_id = c.id
JOIN topics t ON c.topic_id = t.id
JOIN units u ON t.unit_id = u.id
WHERE u.course_id = :course_id
GROUP BY c.id, c.name, c.difficulty, c.importance
HAVING AVG(p.average_score) < 60.0
ORDER BY avg_score ASC;

-- 4. Scheduled Assessment Pipeline
-- Lists pending tests, mapped questions count, and total maximum marks.
-- Features: LEFT JOIN, GROUP BY
SELECT a.id, a.title, a.assessment_type, a.max_marks, a.scheduled_date, a.status,
       COUNT(q.id) AS question_count
FROM assessments a
LEFT JOIN questions q ON q.assessment_id = a.id
WHERE a.course_id = :course_id AND a.status = 'upcoming'
GROUP BY a.id, a.title, a.assessment_type, a.max_marks, a.scheduled_date, a.status
ORDER BY a.scheduled_date ASC;

-- 5. Completed Teaching Session Logs
-- Displays recorded classroom delivery, pedagogical methods utilized, and duration.
-- Features: Multi-table JOIN, LEFT JOIN
SELECT cs.session_number, t.title AS topic_taught, tm.name AS method_utilized,
       ts.actual_minutes, ts.student_engagement_rating, ts.teacher_notes, ts.conducted_at
FROM class_sessions cs
JOIN teaching_sessions ts ON ts.session_id = cs.id
LEFT JOIN topics t ON cs.current_topic_id = t.id
LEFT JOIN teaching_methods tm ON ts.method_id = tm.id
WHERE cs.course_id = :course_id
ORDER BY cs.session_number DESC;

-- 6. Course Progress & Session Ratio
-- Computes exact percentage of completed periods against total budgeted sessions.
-- Features: Conditional aggregation (CASE)
SELECT c.total_classes,
       COUNT(CASE WHEN cs.status = 'completed' THEN 1 END) AS completed_periods,
       COUNT(CASE WHEN cs.status = 'scheduled' THEN 1 END) AS pending_periods,
       ROUND((COUNT(CASE WHEN cs.status = 'completed' THEN 1 END)::numeric / c.total_classes * 100), 1) AS progress_pct
FROM courses c
JOIN class_sessions cs ON cs.course_id = c.id
WHERE c.id = :course_id
GROUP BY c.id, c.total_classes;

-- 7. Prerequisite Bottleneck Concepts
-- Concepts that are a direct prerequisite for two or more other concepts, lowest cohort score first.
-- Features: Self-referencing M:N, HAVING
SELECT p_concept.name AS bottleneck_concept,
       COUNT(DISTINCT prereq.concept_id) AS downstream_dependent_concepts,
       ROUND(AVG(p.average_score)::numeric, 1) AS cohort_score
FROM prerequisites prereq
JOIN concepts p_concept ON prereq.prerequisite_id = p_concept.id
LEFT JOIN performance p ON p.concept_id = p_concept.id
JOIN topics t ON p_concept.topic_id = t.id
JOIN units u ON t.unit_id = u.id
WHERE u.course_id = :course_id
GROUP BY p_concept.id, p_concept.name
HAVING COUNT(DISTINCT prereq.concept_id) >= 2
ORDER BY downstream_dependent_concepts DESC, cohort_score ASC;

-- 8. Empirical Teaching Method Gain Analysis
-- Evaluates observed student learning gains across teaching methodology styles.
-- Features: JOIN, ORDER BY
SELECT tm.name AS teaching_method, me.concept_type,
       me.baseline_score, me.post_score, me.observed_gain,
       me.sample_sessions_count
FROM method_effectiveness me
JOIN teaching_methods tm ON me.method_id = tm.id
ORDER BY me.observed_gain DESC;

-- 9. Topic-Level Planned vs Allocated Time
-- Compares syllabus estimated base time against optimizer-allocated instructional minutes.
-- Features: Derived columns
SELECT t.title AS topic_title, t.estimated_minutes AS syllabus_estimate,
       t.allocated_minutes AS optimizer_allocated,
       (t.allocated_minutes - t.estimated_minutes) AS allocation_variance,
       t.priority_score
FROM topics t
JOIN units u ON t.unit_id = u.id
WHERE u.course_id = :course_id
ORDER BY t.priority_score DESC;

-- 10. Immediate Revision Priority Queue
-- Identifies concepts mapped to upcoming sessions whose prerequisite average is under threshold.
-- Features: Six-way JOIN, DISTINCT
SELECT DISTINCT c_prereq.name AS revision_target_concept,
       p.average_score AS recorded_score,
       p.common_errors,
       t_target.title AS blocking_for_topic
FROM class_sessions cs
JOIN topics t_target ON cs.current_topic_id = t_target.id
JOIN concepts c_target ON c_target.topic_id = t_target.id
JOIN prerequisites pr ON pr.concept_id = c_target.id
JOIN concepts c_prereq ON pr.prerequisite_id = c_prereq.id
JOIN performance p ON p.concept_id = c_prereq.id
WHERE cs.course_id = :course_id AND cs.status = 'scheduled' AND p.average_score < 60.0
ORDER BY p.average_score ASC;

-- 11. Curriculum Depth via Recursive CTE
-- Walks the prerequisite DAG from root concepts with WITH RECURSIVE and keeps each concept's longest chain (ROW_NUMBER window) - the concept's depth in the curriculum.
-- Features: WITH RECURSIVE, Window function (ROW_NUMBER), NOT EXISTS
WITH RECURSIVE chain (concept_id, depth, path) AS (
    SELECT c.id, 0, CAST(c.name AS TEXT)
    FROM concepts c
    JOIN topics t ON t.id = c.topic_id
    JOIN units u ON u.id = t.unit_id
    WHERE u.course_id = :course_id
      AND NOT EXISTS (SELECT 1 FROM prerequisites p WHERE p.concept_id = c.id)
    UNION ALL
    SELECT p.concept_id, ch.depth + 1, ch.path || ' -> ' || c.name
    FROM chain ch
    JOIN prerequisites p ON p.prerequisite_id = ch.concept_id
    JOIN concepts c ON c.id = p.concept_id
),
ranked AS (
    SELECT ch.concept_id, ch.depth, ch.path,
           ROW_NUMBER() OVER (PARTITION BY ch.concept_id ORDER BY ch.depth DESC) AS rn
    FROM chain ch
)
SELECT c.name AS concept, r.depth AS curriculum_depth, r.path AS longest_prerequisite_path
FROM ranked r
JOIN concepts c ON c.id = r.concept_id
WHERE r.rn = 1
ORDER BY r.depth DESC, c.name;

-- 12. Topic Priority Rank & Running Time Budget
-- RANK() within each unit plus a running SUM() of allocated minutes shows where in the syllabus the time budget is consumed.
-- Features: Window function (RANK, PARTITION BY), Running total (SUM OVER ROWS)
SELECT u.unit_number, t.title AS topic_title, t.priority_score, t.allocated_minutes,
       RANK() OVER (PARTITION BY u.id ORDER BY t.priority_score DESC) AS rank_in_unit,
       SUM(t.allocated_minutes) OVER (
           ORDER BY u.unit_number, t.order_index
           ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
       ) AS cumulative_minutes,
       ROUND(100.0 * SUM(t.allocated_minutes) OVER (
           ORDER BY u.unit_number, t.order_index
           ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
       ) / c.total_available_minutes, 1) AS pct_of_course_budget
FROM topics t
JOIN units u ON u.id = t.unit_id
JOIN courses c ON c.id = u.course_id
WHERE c.id = :course_id
ORDER BY u.unit_number, t.order_index;

-- 13. Concept Score Trend Across Assessments
-- LAG() compares each concept's score with its previous assessment to show improvement or decline over time.
-- Features: Window function (LAG)
SELECT c.name AS concept, a.title AS assessment, a.scheduled_date, p.average_score,
       LAG(p.average_score) OVER (PARTITION BY c.id ORDER BY a.scheduled_date) AS previous_score,
       p.average_score - LAG(p.average_score) OVER (PARTITION BY c.id ORDER BY a.scheduled_date) AS change
FROM performance p
JOIN assessments a ON a.id = p.assessment_id
JOIN concepts c ON c.id = p.concept_id
WHERE a.course_id = :course_id
ORDER BY c.name, a.scheduled_date;

-- 14. Fully Assessed Topics (Relational Division)
-- Relational division with double NOT EXISTS: topics for which there is no concept that lacks an assessment result.
-- Features: Relational division, Correlated NOT EXISTS
SELECT u.unit_number, t.title AS topic_title,
       (SELECT COUNT(*) FROM concepts c WHERE c.topic_id = t.id) AS concepts
FROM topics t
JOIN units u ON u.id = t.unit_id
WHERE u.course_id = :course_id
  AND EXISTS (SELECT 1 FROM concepts c WHERE c.topic_id = t.id)
  AND NOT EXISTS (
      SELECT 1 FROM concepts c
      WHERE c.topic_id = t.id
        AND NOT EXISTS (SELECT 1 FROM performance p WHERE p.concept_id = c.id)
  )
ORDER BY u.unit_number, t.order_index;

-- 15. Prerequisites Never Assessed (EXCEPT)
-- Set difference: concepts other topics depend on, minus concepts that have any assessment evidence - blind spots in the feedback loop.
-- Features: Set operation (EXCEPT)
SELECT c.name AS prerequisite_concept
FROM concepts c
JOIN topics t ON t.id = c.topic_id
JOIN units u ON u.id = t.unit_id
WHERE u.course_id = :course_id
  AND c.id IN (SELECT prerequisite_id FROM prerequisites)
EXCEPT
SELECT c.name
FROM concepts c
JOIN performance p ON p.concept_id = c.id
ORDER BY 1;

-- 16. Concept Mastery (View) [PostgreSQL]
-- Reads the v_concept_mastery view: latest vs previous score, transitive downstream dependents (recursive CTE), and a mastery status derived with the course's own threshold.
-- Features: View, LATERAL join, Recursive CTE (inside view)
SELECT unit_number, topic_title, concept_name, assessments_count, avg_score,
       latest_score, score_trend, downstream_count, mastery_status
FROM v_concept_mastery
WHERE course_id = :course_id
ORDER BY CASE mastery_status
             WHEN 'bottleneck' THEN 1 WHEN 'weak' THEN 2 WHEN 'moderate' THEN 3
             WHEN 'strong' THEN 4 ELSE 5 END,
         avg_score NULLS LAST;

-- 17. Time Pressure (Stored Function) [PostgreSQL]
-- Calls fn_time_pressure(): remaining curriculum demand vs remaining scheduled capacity.
-- Features: Set-returning function
SELECT * FROM fn_time_pressure(:course_id);

-- 18. Course Dashboard (Materialized View) [PostgreSQL]
-- Reads the precomputed mv_course_dashboard snapshot; refreshed with REFRESH MATERIALIZED VIEW CONCURRENTLY.
-- Features: Materialized view
SELECT code, total_topics, completed_topics, topic_completion_pct, session_completion_pct,
       taught_minutes, remaining_minutes, weak_concepts, bottleneck_concepts,
       pressure_ratio, pressure_status, refreshed_at
FROM mv_course_dashboard
WHERE course_id = :course_id;

-- 19. Audit Trail (Trigger-Populated) [PostgreSQL]
-- Recent changes captured by the fn_audit_row_change() trigger, with the changed fields computed by diffing the JSONB row images.
-- Features: Trigger, JSONB, jsonb_each
SELECT a.changed_at, a.table_name, a.operation, a.row_id,
       COALESCE(u.email, 'system') AS changed_by,
       (SELECT string_agg(n.key, ', ' ORDER BY n.key)
        FROM jsonb_each(a.new_data) n
        WHERE a.old_data IS NOT NULL
          AND n.value IS DISTINCT FROM a.old_data -> n.key) AS changed_fields
FROM audit_log a
LEFT JOIN users u ON u.id = a.changed_by
WHERE COALESCE(a.new_data, a.old_data) ->> 'course_id' = :course_id
   OR a.row_id = :course_id
ORDER BY a.id DESC
LIMIT 25;
