"""
Regenerate the reference SQL files from their sources of truth:

  database/sql/01_schema.sql        <- pg_dump --schema-only of a migrated database
  database/sql/02_demo_queries.sql  <- DEMO_QUERIES in app/services/dbms_insights_service.py

Usage (repo root, PostgreSQL migrated to head):
    python database/scripts/export_sql_reference.py

pg_dump is looked up on PATH, then in the default Windows install location;
override with PG_DUMP=/path/to/pg_dump.
"""
import os
import shutil
import subprocess
import sys
from pathlib import Path

from sqlalchemy.engine import make_url

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "backend"))

from app.database.config import settings  # noqa: E402
from app.services.dbms_insights_service import DEMO_QUERIES  # noqa: E402

SCHEMA_HEADER = """\
-- ===================================================================
-- OptiTeach: PostgreSQL relational schema (reference DDL)
--
-- GENERATED by database/scripts/export_sql_reference.py from a database
-- migrated with `alembic upgrade head`. Includes tables, constraints,
-- indexes, views, the materialized view, functions, the procedure and
-- triggers. Source of truth is database/migrations/ - regenerate, don't edit.
-- ===================================================================

"""

QUERIES_HEADER = """\
-- ===================================================================
-- OptiTeach: SQL demonstration queries (as run by the DBMS Insights page)
--
-- GENERATED by database/scripts/export_sql_reference.py from
-- backend/app/services/dbms_insights_service.py - regenerate, don't edit.
-- :course_id is a bound parameter; queries marked [PostgreSQL] use
-- server-side objects created in migration 0002.
-- ===================================================================
"""


def find_pg_dump() -> str:
    candidates = [os.getenv("PG_DUMP"), shutil.which("pg_dump")]
    candidates += sorted(Path("C:/Program Files/PostgreSQL").glob("*/bin/pg_dump.exe"), reverse=True)
    for c in candidates:
        if c and Path(c).exists():
            return str(c)
    sys.exit("pg_dump not found; set PG_DUMP")


def export_schema() -> None:
    url = make_url(settings.DATABASE_URL)
    if not url.drivername.startswith("postgresql"):
        sys.exit(f"DATABASE_URL must point at PostgreSQL, got {url.drivername}")
    dump = subprocess.run(
        [find_pg_dump(), "--schema-only", "--no-owner", "--no-privileges",
         "-T", "alembic_version", "-h", url.host or "localhost", "-p", str(url.port or 5432),
         "-U", url.username, url.database],
        env={**os.environ, "PGPASSWORD": url.password or ""},
        check=True, capture_output=True, text=True,
    ).stdout

    kept, blank = [], False
    for line in dump.splitlines():
        # Keep pg_dump's SET lines (check_function_bodies = false lets SQL functions be
        # created before the tables they reference); drop the banner and psql-only guards
        if line.startswith(("-- Dumped ", "\\restrict", "\\unrestrict")):
            continue
        if not line.strip():
            if blank:
                continue
            blank = True
        else:
            blank = False
        kept.append(line)
    (ROOT / "database/sql/01_schema.sql").write_text(SCHEMA_HEADER + "\n".join(kept).strip() + "\n", encoding="utf-8")


def export_queries() -> None:
    parts = [QUERIES_HEADER]
    for q in DEMO_QUERIES:
        tag = " [PostgreSQL]" if q.get("requires") == "postgresql" else ""
        features = ", ".join(q.get("sql_features", []))
        sql = "\n".join(line[8:] if line.startswith("        ") else line for line in q["sql"].strip("\n").splitlines())
        parts.append(f"\n-- {q['title']}{tag}\n-- {q['purpose']}\n-- Features: {features}\n{sql.strip()}\n")
    (ROOT / "database/sql/02_demo_queries.sql").write_text("".join(parts), encoding="utf-8")


if __name__ == "__main__":
    export_schema()
    export_queries()
    print("Wrote database/sql/01_schema.sql and database/sql/02_demo_queries.sql")
