import uuid
from typing import Dict, Any, Optional
from datetime import datetime, timezone
from sqlalchemy.orm import Session
from sqlalchemy.orm.exc import StaleDataError
from app.models.entities import LessonPlan, ClassSession, Topic, Concept, generate_uuid
from app.database.connection import get_mongo_db
from app.schemas.schemas import LessonPlanCreate, LessonPlanOut, LessonPlanUpdate, PeriodPhase
from app.services.errors import ConflictError

class LessonPlanService:
    """
    Polyglot Lesson Plan Service.
    Saves authoritative relational references in PostgreSQL (lesson_plans table)
    and flexible rich pedagogical artifacts in MongoDB (lesson_plan_documents collection).
    """

    def generate_plan(self, db: Session, course_id: str, session_number: int, class_plan_data: Dict[str, Any]) -> LessonPlanOut:
        mongo_db = get_mongo_db()
        session = (
            db.query(ClassSession)
            .filter(ClassSession.course_id == course_id, ClassSession.session_number == session_number)
            .first()
        )
        if not session:
            raise ValueError(f"Session {session_number} not found for course {course_id}")

        topic = db.query(Topic).filter(Topic.id == class_plan_data["topic_id"]).first()
        if not topic:
            raise ValueError(f"Topic {class_plan_data['topic_id']} not found")

        # Synthesize domain-specific pedagogical content
        objectives = [
            f"Understand core principles, formal definitions, and mechanics of {topic.title}.",
            f"Formulate and solve standard analytical problems related to {topic.title}.",
            f"Recognize practical trade-offs and edge cases encountered in real-world database systems."
        ]

        worked_examples = [
            f"Worked Example 1: Basic execution and verification algorithm for {topic.title}.",
            f"Worked Example 2: Edge-case problem involving decomposed schemas and constraint preservation."
        ]

        active_exercises = [
            f"Think-Pair-Share: Analyze sample relation R(A,B,C,D) and identify violations for {topic.title}.",
            "Individual Exit Ticket: Solve 5-minute decomposition problem before session end."
        ]

        misconceptions = [
            "Confusing candidate keys with superkeys during minimal cover derivation.",
            "Assuming every 3NF decomposition is automatically dependency preserving without checking."
        ]

        assessment_questions = [
            f"State the primary definition and condition required for {topic.title}.",
            "Given relation R(A, B, C, D, E) with FDs: A->B, BC->D, D->E, determine the highest normal form."
        ]

        existing = db.query(LessonPlan).filter(LessonPlan.session_id == session.id).first()
        lp_entity = existing or LessonPlan(id=generate_uuid(), session_id=session.id)

        # 1. Rich document in MongoDB (a new version document, never an in-place overwrite)
        doc_payload = {
            "course_id": course_id,
            "session_number": session_number,
            "topic_id": topic.id,
            "topic_title": topic.title,
            "phases": [p if isinstance(p, dict) else p.dict() for p in class_plan_data["phases"]],
            "learning_objectives": objectives,
            "worked_examples": worked_examples,
            "active_exercises": active_exercises,
            "misconceptions": misconceptions,
            "assessment_questions": assessment_questions,
            "why_explanation": class_plan_data.get("why_explanation", ""),
            "generated_at": datetime.now(timezone.utc).isoformat()
        }
        mongo_doc_id = self._insert_version_doc(
            mongo_db, lp_entity, doc_payload, change_note="Generated by optimizer", edited_by=None
        )

        # 2. Relational pointer in PostgreSQL. AI output is only a recommendation, so it
        #    starts as a draft until the teacher approves it.
        lp_entity.topic_id = topic.id
        lp_entity.title = f"Lesson Plan: {topic.title} (Period {session_number})"
        lp_entity.mongo_doc_id = mongo_doc_id
        lp_entity.status = "draft"
        lp_entity.teacher_overridden = False
        if not existing:
            db.add(lp_entity)
        self._commit_or_compensate(db, mongo_db, mongo_doc_id)

        return self.get_plan(db, session.id)

    # ------------------------------------------------------------------
    # Polyglot write helpers
    # ------------------------------------------------------------------
    @staticmethod
    def _insert_version_doc(mongo_db, lp: LessonPlan, content: Dict[str, Any], change_note: str, edited_by: Optional[str]) -> str:
        """Every save is a new immutable document; lesson_plans.mongo_doc_id points at the current one."""
        doc_id = str(uuid.uuid4())
        mongo_db["lesson_plan_documents"].insert_one({
            **{k: v for k, v in content.items() if k not in ("_id", "version", "parent_doc_id", "lesson_plan_id",
                                                           "change_note", "edited_by", "edited_at")},
            "_id": doc_id,
            "lesson_plan_id": lp.id,
            "version": (lp.version or 0) + 1,
            "parent_doc_id": lp.mongo_doc_id,
            "change_note": change_note,
            "edited_by": edited_by,
            "edited_at": datetime.now(timezone.utc).isoformat(),
        })
        return doc_id

    @staticmethod
    def _commit_or_compensate(db: Session, mongo_db, new_doc_id: str) -> None:
        """
        MongoDB and PostgreSQL share no transaction, so the order is: write the new document,
        then commit the SQL pointer. If the commit fails (including a lost optimistic-lock
        race), the compensating action deletes the document so no orphan is left behind.
        """
        try:
            db.commit()
        except StaleDataError:
            db.rollback()
            mongo_db["lesson_plan_documents"].delete_one({"_id": new_doc_id})
            raise ConflictError("This lesson plan was changed by someone else. Reload and try again.")
        except Exception:
            db.rollback()
            mongo_db["lesson_plan_documents"].delete_one({"_id": new_doc_id})
            raise

    def update_plan(self, db: Session, course_id: str, session_number: int,
                    payload: LessonPlanUpdate, user_id: str) -> LessonPlanOut:
        """Teacher accepts / edits / rejects a recommended plan (human-in-the-loop)."""
        session = (
            db.query(ClassSession)
            .filter(ClassSession.course_id == course_id, ClassSession.session_number == session_number)
            .first()
        )
        lp = db.query(LessonPlan).filter(LessonPlan.session_id == session.id).first() if session else None
        if not lp:
            raise ValueError(f"Lesson plan for session {session_number} not found")

        # First line of defence: the version the client saw. The second is the versioned
        # UPDATE itself, which catches a save that lands between this check and our commit.
        if lp.version != payload.expected_version:
            raise ConflictError(
                "This lesson plan was changed by someone else. Reload and try again.",
                current_version=lp.version,
            )

        edits = payload.model_dump(
            exclude_unset=True, exclude={"expected_version", "status", "change_note"}
        )
        if "phases" in edits:
            total = sum(p["duration_minutes"] for p in edits["phases"])
            if any(p["duration_minutes"] <= 0 for p in edits["phases"]) or total != session.duration_minutes:
                raise ValueError(
                    f"Phase durations must be positive and add up to the {session.duration_minutes}-minute period "
                    f"(got {total})"
                )

        mongo_db = get_mongo_db()
        current = mongo_db["lesson_plan_documents"].find_one({"_id": lp.mongo_doc_id}) or {}
        new_doc_id = self._insert_version_doc(
            mongo_db, lp, {**current, **edits},
            change_note=payload.change_note or (f"Status set to {payload.status}" if payload.status else "Edited"),
            edited_by=user_id,
        )

        lp.mongo_doc_id = new_doc_id
        if edits:
            lp.teacher_overridden = True
            lp.status = payload.status or "modified"
        elif payload.status:
            lp.status = payload.status
        self._commit_or_compensate(db, mongo_db, new_doc_id)
        return self.get_plan(db, session.id)

    def get_plan(self, db: Session, session_id: str) -> Optional[LessonPlanOut]:
        lp = db.query(LessonPlan).filter(LessonPlan.session_id == session_id).first()
        if not lp:
            return None

        mongo_db = get_mongo_db()
        doc = mongo_db["lesson_plan_documents"].find_one({"_id": lp.mongo_doc_id})
        phases = [PeriodPhase(**p) for p in doc.get("phases", [])] if doc else []

        return LessonPlanOut(
            id=lp.id,
            session_id=lp.session_id,
            session_number=lp.session.session_number if lp.session else 1,
            topic_id=lp.topic_id,
            topic_title=lp.topic.title if lp.topic else "",
            title=lp.title,
            status=lp.status,
            teacher_overridden=lp.teacher_overridden,
            phases=phases,
            learning_objectives=doc.get("learning_objectives", []) if doc else [],
            worked_examples=doc.get("worked_examples", []) if doc else [],
            active_exercises=doc.get("active_exercises", []) if doc else [],
            misconceptions=doc.get("misconceptions", []) if doc else [],
            assessment_questions=doc.get("assessment_questions", []) if doc else [],
            version=lp.version,
            created_at=lp.created_at
        )

    def list_plans(
        self,
        db: Session,
        course_id: str,
        session_number: Optional[int] = None,
        unit_id: Optional[str] = None,
        topic_id: Optional[str] = None,
        status: Optional[str] = None
    ) -> list[LessonPlanOut]:
        query = (
            db.query(LessonPlan)
            .join(ClassSession)
            .filter(ClassSession.course_id == course_id)
        )
        if session_number is not None:
            query = query.filter(ClassSession.session_number == session_number)
        if topic_id:
            query = query.filter(LessonPlan.topic_id == topic_id)
        if status:
            query = query.filter(LessonPlan.status == status)
        if unit_id:
            query = query.join(Topic).filter(Topic.unit_id == unit_id)

        existing_plans = query.order_by(ClassSession.session_number).all()

        # If specific session requested or no plans exist at all, generate dynamically
        if not existing_plans:
            from app.optimization.class_optimizer import class_optimizer
            target_session = session_number if session_number is not None else 1
            try:
                opt = class_optimizer.optimize_next_class(db, course_id, session_number=target_session)
                generated = self.generate_plan(db, course_id, target_session, opt.dict())
                return [generated]
            except Exception:
                return []

        results = []
        for lp in existing_plans:
            plan_out = self.get_plan(db, lp.session_id)
            if plan_out:
                results.append(plan_out)
        return results

lesson_plan_service = LessonPlanService()
